models:
  - type: main
    engine: openai
    model: openrouter/free
    api_key_env_var: OPENROUTER_API_KEY
    parameters:
      base_url: "https://openrouter.ai/api/v1"

  - type: embeddings
    engine: SentenceTransformers
    model: NeuML/bioclinical-modernbert-base-embeddings